database:
  connection-string: ""

server:
  mode: ""
  address: ""

app:
  issuer: ""
  valid: 0

pki:
  public-key: ""
  private-key: ""

s3:
  endpoint: ""
  bucket: ""
  aws-access-key-id: ""
  aws-secret-access-key: ""
  aws-default-region: ""